// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hklgyjekjtnhmpqrkfdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrbGd5amVranRuaG1wcXJrZmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzgzMDYsImV4cCI6MjA3MTIxNDMwNn0.clv9NOxyHMfsRnHXPeLk5yBtWHcRP9KE3lrE0Q_Giqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});